version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: ""
      ACCEPT_EULA: "Y"
